<?php
require_once 'include/database/PearDatabase.php';
require_once 'vtlib/Vtiger/Utils.php';

if (!$db) {
    $db = PearDatabase::getInstance();
}

//0 = on, 1 = off. Why? Because vTiger.
$profiles = [
    'Administrator' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Parent Van Line User' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Child Van Line User' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Sales Manager' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Support Manager' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Coordinator' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Salesperson' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Read-Only User' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'EditView'   => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
];

//Dependent modules that require matching permissions
$dependentModules = [
    'Opportunities' => ['Potentials'],
    'Estimates'     => ['Quotes'],
    'Tariffs'       => ['EffectiveDates',
                        'TariffReportSections',
                        'TariffSections',
                        'TariffServices']
];

/**********************  Begin creating the permissions  ***********************/

//Remove permissions and recreate them
Vtiger_Utils::ExecuteQuery("TRUNCATE `vtiger_profile2standardpermissions`");

foreach ($profiles as $profileName => $profileDetails) {           //Profiles
    foreach ($profileDetails as $tabName => $tabPermissions) {   //Tabs
        foreach ($tabPermissions as $permissionName => $value) { //Permissions

            //If they don't have access to the module, then we have to update their profile/tab relation
            if ($permissionName == 'index' && $value == 1) {
                Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_profile2tab` SET `permissions` = 1 WHERE `profileid` = (SELECT `profileid` FROM `vtiger_profile` WHERE `profilename` = '$profileName') AND `tabid` = (SELECT `tabid` FROM `vtiger_tab` WHERE `name` = '$tabName')");
            } elseif ($permissionName == 'index' && $value == 0) {
                //Just in case we have turned on a previous module that was turned off
                Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_profile2tab` SET `permissions` = 0 WHERE `profileid` = (SELECT `profileid` FROM `vtiger_profile` WHERE `profilename` = '$profileName') AND `tabid` = (SELECT `tabid` FROM `vtiger_tab` WHERE `name` = '$tabName')");
            }

            insertPermission($profileName, $tabName, $permissionName, $value);

            //Dependent moduels that require the same permissions
            foreach ($dependentModules[$tabName] as $dependentTab) {
                insertPermission($profileName, $dependentTab, $permissionName, $value);
            }
        }
    }
}

//Enable/Disable tabs
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_tab` SET `presence` = 0");
foreach ($tabs as $tab) {
    if ($tab == 'Events') {
        //Modules that need presence of 2
        Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_tab` SET `presence` = 2 WHERE `name` = '$tab'");
    } else {
        //Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_tab` SET `presence` = 0 WHERE `name` = '$tab'");
    }
}

function insertPermission($profileName, $tabName, $permissionName, $value)
{
    $db = PearDatabase::getInstance();

    $sql = 'INSERT INTO `vtiger_profile2standardpermissions` (profileid,
															  tabid,
															  operation,
															  permissions)

			VALUES( (SELECT `profileid` FROM `vtiger_profile` WHERE `profilename` = ?),
					(SELECT `tabid` FROM `vtiger_tab` WHERE `name` = ?),
					(SELECT `actionid` FROM `vtiger_actionmapping` WHERE `actionname` = ?),
					?)';

    $db->pquery($sql, [$profileName, $tabName, $permissionName, $value]);
}
