<?php

return [
    'Account'    => 'LBL_CONTACTS_ACCOUNTS::LBL_CONTACT_INFORMATION::LBL_CUSTOMER_PORTAL_INFORMATION::LBL_ADDRESS_INFORMATION::LBL_DESCRIPTION_INFORMATION::LBL_IMAGE_INFORMATION',
    'Agent'      => 'LBL_CONTACTS_AGENTS::LBL_CONTACT_INFORMATION::LBL_CUSTOMER_PORTAL_INFORMATION::LBL_ADDRESS_INFORMATION::LBL_DESCRIPTION_INFORMATION::LBL_IMAGE_INFORMATION',
    'Transferee' => 'LBL_CONTACT_INFORMATION::LBL_CUSTOMER_PORTAL_INFORMATION::LBL_ADDRESS_INFORMATION::LBL_DESCRIPTION_INFORMATION::LBL_IMAGE_INFORMATION',
    'Vanline'    => 'LBL_CONTACTS_VANLINES::LBL_CONTACT_INFORMATION::LBL_CUSTOMER_PORTAL_INFORMATION::LBL_ADDRESS_INFORMATION::LBL_DESCRIPTION_INFORMATION::LBL_IMAGE_INFORMATION',
    'Claimant'   => 'LBL_CONTACT_INFORMATION::LBL_CUSTOMER_PORTAL_INFORMATION::LBL_ADDRESS_INFORMATION::LBL_DESCRIPTION_INFORMATION::LBL_IMAGE_INFORMATION'
];
