<?php
if (function_exists("call_ms_function_ver")) {
    $version = '1';
    if (call_ms_function_ver(__FILE__, $version)) {
        //already ran
        print "\e[33mSKIPPING: " . __FILE__ . "<br />\n\e[0m";
        return;
    }
}
print "\e[32mRUNNING: " . __FILE__ . "<br />\n\e[0m";



 //$Vtiger_Utils_Log = true;
//include_once('vtlib/Vtiger/Menu.php');
//include_once('vtlib/Vtiger/Module.php');
//include_once('modules/ModTracker/ModTracker.php');



$estimatesInstance = Vtiger_Module::getInstance('Estimates');
$quotesInstance = Vtiger_Module::getInstance('Quotes');
$field0 = Vtiger_Field::getInstance('shipper_type', $estimatesInstance);
$field1 = Vtiger_Field::getInstance('lead_type', $estimatesInstance);
$field2 = Vtiger_Field::getInstance('move_type', $estimatesInstance);
$field6 = Vtiger_Field::getInstance('effective_tariff', $estimatesInstance);
$field7 = Vtiger_Field::getInstance('business_line_est', $estimatesInstance);
$field10 = Vtiger_Field::getInstance('load_date', $estimatesInstance);
$field12 = Vtiger_Field::getInstance('valuation_deductible', $estimatesInstance);
$field14 = Vtiger_Field::getInstance('valuation_amount', $estimatesInstance);
$field16 = Vtiger_Field::getInstance('lead_type', $estimatesInstance);
$field18 = Vtiger_Field::getInstance('apply_sit_first_day_origin', $estimatesInstance);
$field20 = Vtiger_Field::getInstance('apply_sit_first_day_dest', $estimatesInstance);
$field22 = Vtiger_Field::getInstance('sit_first_day_origin_override', $estimatesInstance);
$field24 = Vtiger_Field::getInstance('sit_first_day_dest_override', $estimatesInstance);
$field26 = Vtiger_Field::getInstance('apply_sit_addl_day_origin', $estimatesInstance);
$field28 = Vtiger_Field::getInstance('apply_sit_addl_day_dest', $estimatesInstance);
$field30 = Vtiger_Field::getInstance('sit_addl_day_origin_override', $estimatesInstance);
$field32 = Vtiger_Field::getInstance('sit_addl_day_dest_override', $estimatesInstance);
$field34 = Vtiger_Field::getInstance('apply_sit_cartage_origin', $estimatesInstance);
$field36 = Vtiger_Field::getInstance('apply_sit_cartage_dest', $estimatesInstance);
$field38 = Vtiger_Field::getInstance('sit_cartage_origin_override', $estimatesInstance);
$field40 = Vtiger_Field::getInstance('sit_cartage_dest_override', $estimatesInstance);
$field42 = Vtiger_Field::getInstance('stair_origin_occurrence', $estimatesInstance);
$field44 = Vtiger_Field::getInstance('elevator_origin_occurrence', $estimatesInstance);
$field46 = Vtiger_Field::getInstance('longcarry_origin_occurrence', $estimatesInstance);
$field48 = Vtiger_Field::getInstance('stair_destination_occurrence', $estimatesInstance);
$field50 = Vtiger_Field::getInstance('elevator_destination_occurrence', $estimatesInstance);
$field52 = Vtiger_Field::getInstance('longcarry_destination_occurrence', $estimatesInstance);
$field54 = Vtiger_Field::getInstance('stair_origin_CTW', $estimatesInstance);
$field56 = Vtiger_Field::getInstance('elevator_origin_CTW', $estimatesInstance);
$field58 = Vtiger_Field::getInstance('longcarry_origin_CTW', $estimatesInstance);
$field60 = Vtiger_Field::getInstance('apply_exlabor_rate_origin', $estimatesInstance);
$field62 = Vtiger_Field::getInstance('apply_exlabor_rate_dest', $estimatesInstance);
$field64 = Vtiger_Field::getInstance('exlabor_rate_origin', $estimatesInstance);
$field66 = Vtiger_Field::getInstance('exlabor_rate_dest', $estimatesInstance);
$field68 = Vtiger_Field::getInstance('exlabor_ot_flat_origin', $estimatesInstance);
$field70 = Vtiger_Field::getInstance('exlabor_ot_flat_dest', $estimatesInstance);
$field72 = Vtiger_Field::getInstance('exlabor_ot_rate_origin', $estimatesInstance);
$field74 = Vtiger_Field::getInstance('exlabor_ot_rate_dest', $estimatesInstance);
$field76 = Vtiger_Field::getInstance('bulky_article_changes', $estimatesInstance);
$field78 = Vtiger_Field::getInstance('rush_shipment_fee', $estimatesInstance);
$field80 = Vtiger_Field::getInstance('accesorial_ot_loading', $estimatesInstance);
$field82 = Vtiger_Field::getInstance('accesorial_ot_unloading', $estimatesInstance);
$field84 = Vtiger_Field::getInstance('accesorial_expedited_service', $estimatesInstance);
$field86 = Vtiger_Field::getInstance('consumption_fuel', $estimatesInstance);
//$field88 = Vtiger_Field::getInstance('express_truckload',$estimatesInstance);
$field90 = Vtiger_Field::getInstance('appliance_service', $estimatesInstance);
$field92 = Vtiger_Field::getInstance('appliance_reservice', $estimatesInstance);
$field94 = Vtiger_Field::getInstance('ori_sit2_date_in', $estimatesInstance);
$field96 = Vtiger_Field::getInstance('des_sit2_date_in', $estimatesInstance);
$field98 = Vtiger_Field::getInstance('ori_sit2_pickup_date', $estimatesInstance);
$field100 = Vtiger_Field::getInstance('des_sit2_pickup_date', $estimatesInstance);
$field102 = Vtiger_Field::getInstance('ori_sit2_number_days', $estimatesInstance);
$field104 = Vtiger_Field::getInstance('des_sit2_number_days', $estimatesInstance);
$field106 = Vtiger_Field::getInstance('ori_sit2_container_or_warehouse', $estimatesInstance);
$field108 = Vtiger_Field::getInstance('des_sit2_container_or_warehouse', $estimatesInstance);
$field110 = Vtiger_Field::getInstance('ori_sit2_container_number', $estimatesInstance);
$field112 = Vtiger_Field::getInstance('des_sit2_container_number', $estimatesInstance);
$field114 = Vtiger_Field::getInstance('space_reserve_cf', $estimatesInstance);
$field116 = Vtiger_Field::getInstance('space_reserve_bool', $estimatesInstance);
$field118 = Vtiger_Field::getInstance('apply_free_fvp', $estimatesInstance);
$field120 = Vtiger_Field::getInstance('min_declared_value_mult', $estimatesInstance);
$field122 = Vtiger_Field::getInstance('free_valuation_limit', $estimatesInstance);
$field124 = Vtiger_Field::getInstance('declared_value', $estimatesInstance);
$field126 = Vtiger_Field::getInstance('valuation_flat_charge', $estimatesInstance);
$field128 = Vtiger_Field::getInstance('rate_per_100', $estimatesInstance);
$field130 = Vtiger_Field::getInstance('free_valuation_type', $estimatesInstance);
$field132 = Vtiger_Field::getInstance('increased_base', $estimatesInstance);
$field134 = Vtiger_Field::getInstance('grr', $estimatesInstance);
$field136 = Vtiger_Field::getInstance('grr_override_amount', $estimatesInstance);
$field138 = Vtiger_Field::getInstance('pricing_color_lock', $estimatesInstance);
$field140 = Vtiger_Field::getInstance('smf_type', $estimatesInstance);
$field142 = Vtiger_Field::getInstance('grr_override', $estimatesInstance);
$field144 = Vtiger_Field::getInstance('grr_cp', $estimatesInstance);
$field146 = Vtiger_Field::getInstance('apply_full_pack_rate_override', $estimatesInstance);
$field148 = Vtiger_Field::getInstance('exlabor_flat_origin', $estimatesInstance);
$field150 = Vtiger_Field::getInstance('exlabor_flat_dest', $estimatesInstance);
$field152 = Vtiger_Field::getInstance('apply_exlabor_ot_rate_origin', $estimatesInstance);
$field154 = Vtiger_Field::getInstance('apply_exlabor_ot_rate_dest', $estimatesInstance);
$field156 = Vtiger_Field::getInstance('stair_destination_CTW', $estimatesInstance);
$field158 = Vtiger_Field::getInstance('elevator_destination_CTW', $estimatesInstance);
$field160 = Vtiger_Field::getInstance('longcarry_destination_CTW', $estimatesInstance);
$field162 = Vtiger_Field::getInstance('ori_sit2_weight', $estimatesInstance);
$field164 = Vtiger_Field::getInstance('des_sit2_weight', $estimatesInstance);

$estimatesblock1 = Vtiger_Block::getInstance('LBL_QUOTE_INFORMATION', $estimatesInstance);
$estimatesblock2 = Vtiger_Block::getInstance('LBL_ADDRESS_INFORMATION', $estimatesInstance);
$estimatesblock3 = Vtiger_Block::getInstance('LBL_QUOTES_VALUATION', $estimatesInstance);
$estimatesblock4 = Vtiger_Block::getInstance('LBL_QUOTES_SITDETAILS', $estimatesInstance);
$estimatesblock5 = Vtiger_Block::getInstance('LBL_QUOTES_STAIR', $estimatesInstance);
$estimatesblock6 = Vtiger_Block::getInstance('LBL_QUOTES_ELEVATOR', $estimatesInstance);
$estimatesblock7 = Vtiger_Block::getInstance('LBL_QUOTES_LONGCARRY', $estimatesInstance);
$estimatesblock8 = Vtiger_Block::getInstance('LBL_QUOTES_ACCESSORIALDETAILS', $estimatesInstance);
$estimatesblock9 = Vtiger_Block::getInstance('LBL_ESTIMATES_APPLIANCE', $estimatesInstance);
$estimatesblock10 = Vtiger_Block::getInstance('LBL_QUOTES_SITDETAILS2', $estimatesInstance);
$estimatesblock11 = Vtiger_Block::getInstance('LBL_SPACE_RESERVATION', $estimatesInstance);
$estimatesblock12 = Vtiger_Block::getInstance('LBL_QUOTES_TPGPRICELOCK', $estimatesInstance);
$estimatesblock13 = Vtiger_Block::getInstance('LBL_QUOTES_INTERSTATEMOVEDETAILS', $estimatesInstance);


$quotesblock1 = Vtiger_Block::getInstance('LBL_QUOTE_INFORMATION', $quotesInstance);
$quotesblock2 = Vtiger_Block::getInstance('LBL_ADDRESS_INFORMATION', $quotesInstance);
$quotesblock3 = Vtiger_Block::getInstance('LBL_QUOTES_VALUATION', $quotesInstance);
$quotesblock4 = Vtiger_Block::getInstance('LBL_QUOTES_SITDETAILS', $quotesInstance);
$quotesblock5 = Vtiger_Block::getInstance('LBL_QUOTES_ACCESSORIALDETAILS', $quotesInstance);
$quotesblock6 = Vtiger_Block::getInstance('LBL_QUOTES_TPGPRICELOCK', $quotesInstance);
$quotesblock7 = Vtiger_Block::getInstance('LBL_QUOTES_INTERSTATEMOVEDETAILS', $quotesInstance);

$field3 = Vtiger_Field::getInstance('shipper_type', $quotesInstance);
$field4 = Vtiger_Field::getInstance('lead_type', $quotesInstance);
$field5 = Vtiger_Field::getInstance('move_type', $quotesInstance);
$field8 = Vtiger_Field::getInstance('effective_tariff', $quotesInstance);
$field9 = Vtiger_Field::getInstance('business_line_est', $quotesInstance);
$field11 = Vtiger_Field::getInstance('load_date', $quotesInstance);
$field13 = Vtiger_Field::getInstance('valuation_deductible', $quotesInstance);
$field15 = Vtiger_Field::getInstance('valuation_amount', $quotesInstance);
$field17 = Vtiger_Field::getInstance('lead_type', $quotesInstance);
$field19 = Vtiger_Field::getInstance('apply_sit_first_day_origin', $quotesInstance);
$field21 = Vtiger_Field::getInstance('apply_sit_first_day_dest', $quotesInstance);
$field23 = Vtiger_Field::getInstance('sit_first_day_origin_override', $quotesInstance);
$field25 = Vtiger_Field::getInstance('sit_first_day_dest_override', $quotesInstance);
$field27 = Vtiger_Field::getInstance('apply_sit_addl_day_origin', $quotesInstance);
$field29 = Vtiger_Field::getInstance('apply_sit_addl_day_dest', $quotesInstance);
$field31 = Vtiger_Field::getInstance('sit_addl_day_origin_override', $quotesInstance);
$field33 = Vtiger_Field::getInstance('sit_addl_day_dest_override', $quotesInstance);
$field35 = Vtiger_Field::getInstance('apply_sit_cartage_origin', $quotesInstance);
$field37 = Vtiger_Field::getInstance('apply_sit_cartage_dest', $quotesInstance);
$field39 = Vtiger_Field::getInstance('sit_cartage_origin_override', $quotesInstance);
$field41 = Vtiger_Field::getInstance('sit_cartage_dest_override', $quotesInstance);
$field43 = Vtiger_Field::getInstance('stair_origin_occurrence', $quotesInstance);
$field45 = Vtiger_Field::getInstance('elevator_origin_occurrence', $quotesInstance);
$field47 = Vtiger_Field::getInstance('longcarry_origin_occurrence', $quotesInstance);
$field49 = Vtiger_Field::getInstance('stair_destination_occurrence', $quotesInstance);
$field51 = Vtiger_Field::getInstance('elevator_destination_occurrence', $quotesInstance);
$field53 = Vtiger_Field::getInstance('longcarry_destination_occurrence', $quotesInstance);
$field55 = Vtiger_Field::getInstance('stair_origin_CTW', $quotesInstance);
$field57 = Vtiger_Field::getInstance('elevator_origin_CTW', $quotesInstance);
$field59 = Vtiger_Field::getInstance('longcarry_origin_CTW', $quotesInstance);
$field61 = Vtiger_Field::getInstance('apply_exlabor_rate_origin', $quotesInstance);
$field63 = Vtiger_Field::getInstance('apply_exlabor_rate_dest', $quotesInstance);
$field65 = Vtiger_Field::getInstance('exlabor_rate_origin', $quotesInstance);
$field67 = Vtiger_Field::getInstance('exlabor_rate_dest', $quotesInstance);
$field69 = Vtiger_Field::getInstance('exlabor_ot_flat_origin', $quotesInstance);
$field71 = Vtiger_Field::getInstance('exlabor_ot_flat_dest', $quotesInstance);
$field73 = Vtiger_Field::getInstance('exlabor_ot_rate_origin', $quotesInstance);
$field75 = Vtiger_Field::getInstance('exlabor_ot_rate_dest', $quotesInstance);
$field77 = Vtiger_Field::getInstance('bulky_article_changes', $quotesInstance);
$field79 = Vtiger_Field::getInstance('rush_shipment_fee', $quotesInstance);
$field81 = Vtiger_Field::getInstance('accesorial_ot_loading', $quotesInstance);
$field83 = Vtiger_Field::getInstance('accesorial_ot_unloading', $quotesInstance);
$field85 = Vtiger_Field::getInstance('accesorial_expedited_service', $quotesInstance);
$field87 = Vtiger_Field::getInstance('consumption_fuel', $quotesInstance);
//$field89 = Vtiger_Field::getInstance('express_truckload',$quotesInstance);
$field91 = Vtiger_Field::getInstance('appliance_service', $quotesInstance);
$field93 = Vtiger_Field::getInstance('appliance_reservice', $quotesInstance);
$field95 = Vtiger_Field::getInstance('ori_sit2_date_in', $quotesInstance);
$field97 = Vtiger_Field::getInstance('des_sit2_date_in', $quotesInstance);
$field99 = Vtiger_Field::getInstance('ori_sit2_pickup_date', $quotesInstance);
$field101 = Vtiger_Field::getInstance('des_sit2_pickup_date', $quotesInstance);
$field103 = Vtiger_Field::getInstance('ori_sit2_number_days', $quotesInstance);
$field105 = Vtiger_Field::getInstance('des_sit2_number_days', $quotesInstance);
$field107 = Vtiger_Field::getInstance('ori_sit2_container_or_warehouse', $quotesInstance);
$field109 = Vtiger_Field::getInstance('des_sit2_container_or_warehouse', $quotesInstance);
$field111 = Vtiger_Field::getInstance('ori_sit2_container_number', $quotesInstance);
$field113 = Vtiger_Field::getInstance('des_sit2_container_number', $quotesInstance);
$field115 = Vtiger_Field::getInstance('space_reserve_cf', $quotesInstance);
$field117 = Vtiger_Field::getInstance('space_reserve_bool', $quotesInstance);
$field119 = Vtiger_Field::getInstance('apply_free_fvp', $quotesInstance);
$field121 = Vtiger_Field::getInstance('min_declared_value_mult', $quotesInstance);
$field123 = Vtiger_Field::getInstance('free_valuation_limit', $quotesInstance);
$field125 = Vtiger_Field::getInstance('declared_value', $quotesInstance);
$field127 = Vtiger_Field::getInstance('valuation_flat_charge', $quotesInstance);
$field129 = Vtiger_Field::getInstance('rate_per_100', $quotesInstance);
$field131 = Vtiger_Field::getInstance('free_valuation_type', $quotesInstance);
$field133 = Vtiger_Field::getInstance('increased_base', $quotesInstance);
$field135 = Vtiger_Field::getInstance('grr', $quotesInstance);
$field137 = Vtiger_Field::getInstance('grr_override_amount', $quotesInstance);
$field139 = Vtiger_Field::getInstance('pricing_color_lock', $quotesInstance);
$field141 = Vtiger_Field::getInstance('smf_type', $quotesInstance);
$field143 = Vtiger_Field::getInstance('grr_override', $quotesInstance);
$field145 = Vtiger_Field::getInstance('grr_cp', $quotesInstance);
$field147 = Vtiger_Field::getInstance('apply_full_pack_rate_override', $quotesInstance);
$field149 = Vtiger_Field::getInstance('exlabor_flat_origin', $quotesInstance);
$field151 = Vtiger_Field::getInstance('exlabor_flat_dest', $quotesInstance);
$field153 = Vtiger_Field::getInstance('apply_exlabor_ot_rate_origin', $quotesInstance);
$field155 = Vtiger_Field::getInstance('apply_exlabor_ot_rate_dest', $quotesInstance);
$field157 = Vtiger_Field::getInstance('stair_destination_CTW', $quotesInstance);
$field159 = Vtiger_Field::getInstance('elevator_destination_CTW', $quotesInstance);
$field161 = Vtiger_Field::getInstance('longcarry_destination_CTW', $quotesInstance);
$field163 = Vtiger_Field::getInstance('ori_sit2_weight', $quotesInstance);
$field165 = Vtiger_Field::getInstance('des_sit2_weight', $quotesInstance);

//Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock1->id . ', defaultvalue = COD'. ' WHERE fieldid = ' . $field0->id);
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET defaultvalue = 'COD' WHERE fieldname = 'shipper_type'");

//Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET defaultvalue = 'COD' WHERE fieldid = ".$fieldid';
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET  quickcreate = 1 WHERE fieldname = 'lead_type'");
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock1->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field4->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock1->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field7->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock1->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field9->id);
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET defaultvalue = 'Interstate' WHERE fieldname = 'move_type'");
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock1->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field10->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock1->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field11->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field12->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field13->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field14->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field15->id);
//Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock1->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field16->id);
//Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock1->id . ', quickcreate = 2'. ' WHERE fieldid = ' . $field17->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field18->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field19->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field20->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field21->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field22->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field23->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field24->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field25->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field26->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field27->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field28->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field29->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field30->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field31->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field32->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field33->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field34->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field35->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field36->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field37->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field38->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field39->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field40->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock4->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field41->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field42->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field43->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock6->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field44->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field45->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock7->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field46->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field47->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field48->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field49->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock6->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field50->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field51->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock7->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field52->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field53->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field54->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field55->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock6->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field56->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field57->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock7->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field58->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field59->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field60->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field61->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field62->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field63->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field64->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field65->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field66->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field67->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field68->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field69->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field70->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field71->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field72->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field73->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field74->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field75->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field76->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field77->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field78->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field79->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field80->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field81->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field82->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field83->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field84->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field85->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field86->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field87->id);
//Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field88->id);
//Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field89->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock9->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field90->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field91->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock9->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field92->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field93->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field94->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field95->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field96->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field97->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field98->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field99->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field100->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field101->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field102->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field103->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field104->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field105->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field106->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field107->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field108->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field109->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field110->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field111->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field112->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field113->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock11->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field114->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field115->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock11->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field116->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field117->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field118->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field119->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field120->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field121->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field122->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field123->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field124->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field125->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field126->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field127->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field128->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field129->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field130->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field131->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field132->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock3->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field133->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock12->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field134->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field135->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock12->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field136->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field137->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock12->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field138->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock6->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field139->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock12->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field140->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock6->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field141->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock12->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field142->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field143->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock12->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field144->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field145->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock13->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field146->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock7->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field147->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field148->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field149->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field150->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field151->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field152->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field153->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock8->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field154->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field155->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field156->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field157->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock6->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field158->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field159->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock7->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field160->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field161->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field162->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field163->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $estimatesblock10->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field164->id);
Vtiger_Utils::ExecuteQuery('UPDATE `vtiger_field` SET block = ' . $quotesblock5->id . ', quickcreate = 1'. ' WHERE fieldid = ' . $field165->id);
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET  quickcreate = 1 WHERE fieldlabel = 'LBL_QUOTES_DESIRED_TOTAL'");
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET  quickcreate = 1 WHERE fieldlabel = 'LBL_ESTIMATES_ORIGINCOUNTY'");
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET  quickcreate = 1 WHERE fieldlabel = 'LBL_ESTIMATES_DESTINATIONCOUNTY'");
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET  quickcreate = 1 WHERE fieldlabel = 'LBL_ESTIMATES_ORIGINCOUNTRY'");
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_field` SET  quickcreate = 1 WHERE fieldlabel = 'LBL_ESTIMATES_DESTINATIONCOUNTRY'");
//updated related list table to show surveys under opportunities
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_relatedlists` SET  name = 'get_dependents_list' WHERE relation_id = 161");

echo "<h1> Updated Estimates QuickCreate</h1>";


print "\e[94mFINISHED: " . __FILE__ . "<br />\n\e[0m";