<?php
class WFAccounts_Detail_View extends Vtiger_Detail_View
{
    function process(Vtiger_Request $request)
    {
        $record     = $request->get('record');
        $viewer     = $this->getViewer($request);
        $singles = ['national_account', 'address_name'];
        $viewer->assign('SINGLE_FIELDS',$singles);
        if(!empty($record)){
            $recordModel = Vtiger_Record_Model::getInstanceById($record);
            $viewer->assign('IMAGE_DETAILS', $recordModel->getImageDetails());
        }
        parent::process($request); // TODO: Change the autogenerated stub
    }
}
