<?php
class WFAccounts_Edit_View extends Vtiger_Edit_View
{
    function getHeaderScripts(Vtiger_Request $request) {
        $headerScriptInstances =  parent::getHeaderScripts($request); // TODO: Change the autogenerated stub
        $wfAddressModel    = Vtiger_Module_Model::getInstance('WFAddress');
        if ($wfAddressModel && $wfAddressModel->isActive()) {
            $jsFileNames[] = "modules.WFAddress.resources.EditBlock";
        }
        $jsScriptInstances     = $this->checkAndConvertJsScripts($jsFileNames);
        $headerScriptInstances = array_merge($headerScriptInstances, $jsScriptInstances);

        return $headerScriptInstances;
    }

    function process(Vtiger_Request $request)
    {
        $record     = $request->get('record');
        $viewer = $this->getViewer($request);
        $singles = ['national_account', 'address_name'];
        $viewer->assign('SINGLE_FIELDS',$singles);
        if(!empty($record)){
            $recordModel = Vtiger_Record_Model::getInstanceById($record);
            $viewer->assign('IMAGE_DETAILS', $recordModel->getImageDetails());
        }
        parent::process($request); // TODO: Change the autogenerated stub
    }
}
