<?php

class Actuals_Edit_View extends Estimates_Edit_View
{
    public function process(Vtiger_Request $request)
    {
        $viewer = $this->getViewer($request);
        $recordId = $request->get('record');
        //logic to include Addresss List
        $addressListModule = Vtiger_Module_Model::getInstance('AddressList');
        if ($addressListModule && $addressListModule->isActive()) {
            $addressListModule->assignValueForAddressList($viewer,$recordId);
        }

        $EscrowsModel=Vtiger_Module_Model::getInstance('Escrows');
        if($EscrowsModel && $EscrowsModel->isActive()) {
            $EscrowsModel->setViewerForEscrowsWithinActual($viewer, $recordId);
        }

        $hiddenBlocks = array('LBL_QUOTES_CONTACTDETAILS');
        $viewer->assign('HIDDEN_BLOCKS', $hiddenBlocks);

        return parent::process($request); // TODO: Change the autogenerated stub
    }
    public function getHeaderScripts(Vtiger_Request $request)
    {
        $headerScriptInstances = parent::getHeaderScripts($request);
        $moduleName = $request->getModule();
        $moduleBaseTariff = 'modules.' . $moduleName . '.resources.BaseTariff';
        $modulePopUpFile = 'modules.' . $moduleName . '.resources.Popup';
        $moduleEditFile = 'modules.' . $moduleName . '.resources.Edit';
        unset($headerScriptInstances[$moduleBaseTariff]);
        unset($headerScriptInstances[$modulePopUpFile]);
        unset($headerScriptInstances[$moduleEditFile]);
        $jsFileNames = [
            'modules.Inventory.resources.Edit',
            'modules.Inventory.resources.Popup',
            //@TODO this will need added and the Actuals/ popup.js needs extended properly.
            //'modules.Estimates.resources.Popup',
            'modules.Quotes.resources.Edit',
            'modules.ExtraStops.resources.EditBlock',
            'modules.Estimates.resources.Edit',
            'modules.Estimates.resources.Common',
            'modules.Estimates.resources.BaseTariff',
            'modules.Escrows.resources.EditBlock',
        ];
        $jsFileNames[] = $moduleEditFile;
        $jsFileNames[] = $modulePopUpFile;
        $jsFileNames[] = "modules.$moduleName.resources.BaseTariff";
        if (getenv('INSTANCE_NAME') == 'sirva') {
            $jsFileNames[] = "modules.$moduleName.resources.TPGTariff";
            $jsFileNames[] = "modules.$moduleName.resources.BaseSIRVA";
            $jsFileNames[] = "modules.Opportunities.resources.MilitaryFields";
        }
        $addressListModule=Vtiger_Module_Model::getInstance('AddressList');
        if ($addressListModule && $addressListModule->isActive()) {
            $jsFileNames[] = "modules.AddressList.resources.EditBlock";
        }
        $jsScriptInstances = $this->checkAndConvertJsScripts($jsFileNames);
        $headerScriptInstances = array_merge($headerScriptInstances, $jsScriptInstances);

        return $headerScriptInstances;
    }
}
