<?php
if (function_exists("call_ms_function_ver")) {
    $version = 'AlwaysRun';
    if (call_ms_function_ver(__FILE__, $version)) {
        //already ran
        print "\e[33mSKIPPING: " . __FILE__ . "<br />\n\e[0m";
        return;
    }
}
print "\e[32mRUNNING: " . __FILE__ . "<br />\n\e[0m";


require_once 'include/database/PearDatabase.php';

if (!$db) {
    $db = PearDatabase::getInstance();
}

//0 = on, 1 = off. Why? Because vTiger.
$profiles = [
    'Administrator' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'Save'       => 0,
            'EditView'   => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Parent Van Line User' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'Save'       => 0,
            'EditView'   => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Child Van Line User' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 0,
            'Save'       => 0,
            'EditView'   => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Sales Manager' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Delete'     => 1,
            'Save'       => 0,
            'EditView'   => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Support Manager' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'EditView'   => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Coordinator' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'SMSNotifier' => [
            'index'      => 0,
            'DetailView' => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'EditView'   => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 1,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Salesperson' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
            'ConvertLead'=> 0,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'SMSNotifier' => [
            'Save'       => 0,
            'index'      => 1,
            'DetailView' => 1,
            'Delete'     => 1,
            'EditView'   => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
    'Read-Only User' => [
        'Calendar' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Reports' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'OPList' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'MailManager' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'TariffManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'AgentManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'VanlineManager' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Leads' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
            'ConvertLead'=> 1,
        ],
        'Estimates' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Surveys' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Campaigns' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Opportunities' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'SMSNotifier' => [
            'index'      => 1,
            'DetailView' => 1,
            'Delete'     => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'EmailTemplates' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Accounts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Contacts' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Agents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Vanlines' => [
            'index'      => 1,
            'DetailView' => 1,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Tariffs' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Documents' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Cubesheets' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 1,
            'Save'       => 1,
            'Delete'     => 1,
            'Import'     => 1,
            'Export'     => 1,
        ],
        'Exchange' => [
            'index'      => 0,
            'DetailView' => 0,
            'EditView'   => 0,
            'Save'       => 0,
            'Delete'     => 0,
            'Import'     => 0,
            'Export'     => 0,
        ],
    ],
];

//Dependent modules that require matching permissions
$dependentModules = [
    'Opportunities' => ['Potentials'],
    'Estimates'     => ['Quotes'],
    'Tariffs'       => ['EffectiveDates',
                        'TariffReportSections',
                        'TariffSections',
                        'TariffServices']
];

if(getenv('INSTANCE_NAME') == 'suddath') {
    $dependentModules['Documents'] = ['Media'];
}

//Tabs to be enabled. Any other tabs will be disabled
$tabs   = array_keys($profiles['Administrator']); //Initial list of tabs
$tabs[] = 'Dashboard';
$tabs[] = 'Potentials';
$tabs[] = 'Home';
$tabs[] = 'Events';
$tabs[] = 'Quotes';
$tabs[] = 'Services';
$tabs[] = 'Import';
$tabs[] = 'ModTracker';
$tabs[] = 'ModComments';
$tabs[] = 'EmailTemplates';
$tabs[] = 'Google';
$tabs[] = 'Webforms';
$tabs[] = 'EffectiveDates';
$tabs[] = 'TariffReportSections';
$tabs[] = 'TariffSections';
$tabs[] = 'TariffServices';
$tabs[] = 'Emails';
$tabs[] = 'Contracts';
$tabs[] = 'Users';
$tabs[] = 'ExtraStops';
$tabs[] = 'ParticipatingAgents';
$tabs[] = 'OASurveyRequests';
$tabs[] = 'Media';

//OT4002 -- national wants this, it'll probably need readdressed if national makes other specifics or other people want it.
if (getenv('INSTANCE_NAME') == 'national') {
    $tabs[] = 'ListviewColors';
}

/**********************  Begin creating the permissions  ***********************/

//Remove permissions and recreate them
Vtiger_Utils::ExecuteQuery("TRUNCATE `vtiger_profile2standardpermissions`");

foreach ($profiles as $profileName => $profileDetails) {           //Profiles
    foreach ($profileDetails as $tabName => $tabPermissions) {   //Tabs
        foreach ($tabPermissions as $permissionName => $value) { //Permissions

            //If they don't have access to the module, then we have to update their profile/tab relation
            if ($permissionName == 'index' && $value == 1) {
                Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_profile2tab` SET `permissions` = 1 WHERE `profileid` = (SELECT `profileid` FROM `vtiger_profile` WHERE `profilename` = '$profileName') AND `tabid` = (SELECT `tabid` FROM `vtiger_tab` WHERE `name` = '$tabName')");
            } elseif ($permissionName == 'index' && $value == 0) {
                //Just in case we have turned on a previous module that was turned off
                Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_profile2tab` SET `permissions` = 0 WHERE `profileid` = (SELECT `profileid` FROM `vtiger_profile` WHERE `profilename` = '$profileName') AND `tabid` = (SELECT `tabid` FROM `vtiger_tab` WHERE `name` = '$tabName')");
            }

            insertPermission($profileName, $tabName, $permissionName, $value);

            //Dependent moduels that require the same permissions
            foreach ($dependentModules[$tabName] as $dependentTab) {
                insertPermission($profileName, $dependentTab, $permissionName, $value);
            }
        }
    }
}

//Enable/Disable tabs
Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_tab` SET `presence` = 1");
foreach ($tabs as $tab) {
    if ($tab == 'Events') {
        //Modules that need presence of 2
        Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_tab` SET `presence` = 2 WHERE `name` = '$tab'");
    } else {
        Vtiger_Utils::ExecuteQuery("UPDATE `vtiger_tab` SET `presence` = 0 WHERE `name` = '$tab'");
    }
}

function insertPermission($profileName, $tabName, $permissionName, $value)
{
    $db = PearDatabase::getInstance();

    $sql = 'INSERT INTO `vtiger_profile2standardpermissions` (profileid,
															  tabid,
															  operation,
															  permissions)

			VALUES( (SELECT `profileid` FROM `vtiger_profile` WHERE `profilename` = ?),
					(SELECT `tabid` FROM `vtiger_tab` WHERE `name` = ?),
					(SELECT `actionid` FROM `vtiger_actionmapping` WHERE `actionname` = ?),
					?)';

    $db->pquery($sql, [$profileName, $tabName, $permissionName, $value]);
}


print "\e[94mFINISHED: " . __FILE__ . "<br />\n\e[0m";