<?php
class WFOrders_Edit_View extends Vtiger_Edit_View
{
    function process(Vtiger_Request $request)
    {

        $viewer = $this->getViewer($request);
        $singles = ['wforder_number'];
        $viewer->assign('SINGLE_FIELDS',$singles);
        if($request->get('record') && $record = Vtiger_Record_Model::getInstanceById($request->get('record'))) {
            $viewer->assign('ORIGINAL_WEIGHT', $record->get('wforder_weight'));
        } else {
            $viewer->assign('ORIGINAL_WEIGHT', 0);
        }
        parent::process($request); // TODO: Change the autogenerated stub
    }
}
