<?php
/**
 * Created by PhpStorm.
 * User: dbolin
 * Date: 3/20/2017
 * Time: 3:06 PM
 */

class Vtiger_AccountingIntegrationReference_UIType extends Vtiger_Base_UIType
{
    public function getTemplateName() {
        return 'uitypes/AccountingIntegrationReference.tpl';
    }

    public function getDisplayValue($value, $record = false, $recordInstance = false) {
        // @TODO: fix this mega hack
        if(!$recordInstance && $value && $_REQUEST['record'])
        {
            $recordInstance = Vtiger_Record_Model::getInstanceById($_REQUEST['record']);
        }
        if($recordInstance && $value)
        {
            $int = new \MoveCrm\AccountingIntegration($recordInstance->get('agentid'));
            return $int->getLabel($value);
            $data = $int->getOne('Customer', $value);
            if($data['entry']['label'])
            {
                return $data['entry']['label'];
            }
        }
        return '';
        //return parent::getDisplayValue($value, $record, $recordInstance); // TODO: Change the autogenerated stub
    }

    public function getEditViewDisplayValue($value)
    {
        // @TODO: fix this mega hack
        if($_REQUEST['record'] && $value)
        {
            $recordModel = Vtiger_Record_Model::getInstanceById($_REQUEST['record']);
            $int = new \MoveCrm\AccountingIntegration($recordModel->get('agentid'));
            return $int->getLabel($value);
            $data = $int->getOne('Customer', $value);
            if($data['entry']['label'])
            {
                return $data['entry']['label'];
            }
        }
        return '';
        //return parent::getEditViewDisplayValue($value);
    }
}


